version: '2.4'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - builders_data:/var/lib/mysql
    mem_limit: 512m

  house-builders:
    image: matheusrdk/house-builders-management-api:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/builders?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    mem_limit: 512m

volumes:
  builders_data: